 const products = [
    {
      id: "1",
      name: "Versace Slim Fit Jeans",
      description: "Luxury slim-fit jeans for a sleek and stylish look.",
      price: 299.99,
      category: "Men",
      tags: ["men", "winter", "casual"],
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "Navy", "Gray"],
      image: "https://via.placeholder.com/200",
      rating: 4.8,
      reviews: 150,
      stock: 25,
      newArrival: true,
      discount: 10,
    },
    {
      id: "2",
      name: "Saint Laurent Leather Biker Jacket",
      description: "Iconic leather jacket for a bold and stylish statement.",
      price: 1999.99,
      category: "Men",
      tags: ["men", "winter", "outerwear"],
      sizes: ["M", "L", "XL"],
      colors: ["Black", "Brown"],
      image: "https://via.placeholder.com/200",
      rating: 4.9,
      reviews: 120,
      stock: 10,
      newArrival: true,
      discount: 15,
    },
    {
      id: "3",
      name: "Louis Vuitton Monogram Handbag",
      description: "A luxurious handbag with the classic monogram design.",
      price: 3499.99,
      category: "Accessories",
      tags: ["women", "accessories", "luxury"],
      sizes: ["One Size"],
      colors: ["Brown", "Beige"],
      image: "https://via.placeholder.com/200",
      rating: 5.0,
      reviews: 80,
      stock: 5,
      newArrival: true,
      discount: 0,
    },
    {
      id: "4",
      name: "Gucci Wool Scarf",
      description: "A soft and warm scarf with a classic Gucci design.",
      price: 599.99,
      category: "Accessories",
      tags: ["accessories", "winter", "luxury"],
      sizes: ["One Size"],
      colors: ["Gray", "Red"],
      image: "https://via.placeholder.com/200",
      rating: 4.7,
      reviews: 50,
      stock: 15,
      newArrival: false,
      discount: 5,
    },
    {
      id: "5",
      name: "Prada Chunky Knit Sweater",
      description: "A cozy and stylish chunky knit sweater.",
      price: 899.99,
      category: "Women",
      tags: ["women", "winter", "luxury"],
      sizes: ["S", "M", "L"],
      colors: ["Cream", "Black"],
      image: "https://via.placeholder.com/200",
      rating: 4.6,
      reviews: 60,
      stock: 20,
      newArrival: false,
      discount: 10,
    },
    {
      id: "6",
      name: "Chanel Silk Evening Dress",
      description: "A stunning evening dress crafted from fine silk.",
      price: 4999.99,
      category: "Women",
      tags: ["women", "luxury", "summer"],
      sizes: ["S", "M", "L"],
      colors: ["Red", "White", "Navy"],
      image: "https://via.placeholder.com/200",
      rating: 4.9,
      reviews: 40,
      stock: 8,
      newArrival: true,
      discount: 20,
    },
    {
      id: "7",
      name: "Hermès Leather Belt",
      description: "A classic Hermès leather belt with iconic buckle design.",
      price: 799.99,
      category: "Accessories",
      tags: ["men", "accessories", "luxury"],
      sizes: ["M", "L", "XL"],
      colors: ["Black", "Brown"],
      image: "https://via.placeholder.com/200",
      rating: 4.8,
      reviews: 90,
      stock: 30,
      newArrival: false,
      discount: 0,
    },
    {
      id: "8",
      name: "Burberry Trench Coat",
      description: "A timeless trench coat with Burberry's signature check lining.",
      price: 2499.99,
      category: "Men",
      tags: ["men", "winter", "outerwear"],
      sizes: ["M", "L", "XL"],
      colors: ["Beige", "Black"],
      image: "https://via.placeholder.com/200",
      rating: 4.9,
      reviews: 70,
      stock: 12,
      newArrival: false,
      discount: 10,
    },
    {
      id: "9",
      name: "Dolce & Gabbana Floral Maxi Dress",
      description: "A vibrant floral dress perfect for summer occasions.",
      price: 1999.99,
      category: "Women",
      tags: ["women", "summer", "luxury"],
      sizes: ["S", "M", "L"],
      colors: ["Yellow", "Pink"],
      image: "https://via.placeholder.com/200",
      rating: 4.7,
      reviews: 30,
      stock: 10,
      newArrival: true,
      discount: 15,
    },
    {
      id: "10",
      name: "Tom Ford Classic Sunglasses",
      description: "Elegant sunglasses for a stylish look.",
      price: 599.99,
      category: "Accessories",
      tags: ["unisex", "accessories", "summer"],
      sizes: ["One Size"],
      colors: ["Black", "Brown"],
      image: "https://via.placeholder.com/200",
      rating: 4.6,
      reviews: 80,
      stock: 40,
      newArrival: true,
      discount: 5,
    },
    {
      id: "11",
      name: "Moncler Puffer Jacket",
      description: "A warm and lightweight puffer jacket for cold weather.",
      price: 1799.99,
      category: "Men",
      tags: ["men", "winter", "luxury"],
      sizes: ["M", "L", "XL"],
      colors: ["Black", "Navy"],
      image: "https://via.placeholder.com/200",
      rating: 4.8,
      reviews: 100,
      stock: 15,
      newArrival: false,
      discount: 10,
    },
    {
      id: "12",
      name: "Rolex Oyster Perpetual Watch",
      description: "A classic luxury watch with timeless appeal.",
      price: 10999.99,
      category: "Accessories",
      tags: ["unisex", "accessories", "luxury"],
      sizes: ["One Size"],
      colors: ["Silver", "Gold"],
      image: "https://via.placeholder.com/200",
      rating: 5.0,
      reviews: 50,
      stock: 5,
      newArrival: false,
      discount: 0,
    },
    {
      id: "13",
      name: "Balenciaga Oversized Hoodie",
      description: "A statement hoodie with a relaxed oversized fit.",
      price: 899.99,
      category: "Men",
      tags: ["men", "winter", "luxury"],
      sizes: ["M", "L", "XL"],
      colors: ["Gray", "Black"],
      image: "https://via.placeholder.com/200",
      rating: 4.7,
      reviews: 60,
      stock: 25,
      newArrival: false,
      discount: 5,
    },
    {
      id: "14",
      name: "Armani Cashmere Cardigan",
      description: "A luxurious cardigan crafted from soft cashmere.",
      price: 1299.99,
      category: "Women",
      tags: ["women", "winter", "luxury"],
      sizes: ["S", "M", "L"],
      colors: ["Beige", "White"],
      image: "https://via.placeholder.com/200",
      rating: 4.9,
      reviews: 35,
      stock: 15,
      newArrival: true,
      discount: 10,
    },
    {
      id: "15",
      name: "Fendi Embossed Leather Tote",
      description: "A stylish leather tote with embossed Fendi logo.",
      price: 2499.99,
      category: "Accessories",
      tags: ["women", "accessories", "luxury"],
      sizes: ["One Size"],
      colors: ["Black", "Brown"],
      image: "https://via.placeholder.com/200",
      rating: 5.0,
      reviews: 20,
      stock: 8,
      newArrival: true,
      discount: 0,
    },
  ];
  export default products;
  